### ISSUE TITLE
Clinical part error

### ISSUE THREAD

**Issue by kadupena25** [ETH-NEXUS/scAmpi_single_cell_RNA#16]
Hi I am trying to run clinical-only part and it is returning this mensage:

AttributeError: 'Variant' object has no attribute 'civic_actionability_score' 

Any advice?

**Comment by aricht** [comment]
Hi,
off the top of my head I cannot say I have seen this error before.
Could you share a minimum example of your data that triggers this error, and also provide the command that you used?
That would help for further trouble shooting.
