### ISSUE TITLE
Running multiple samples

### ISSUE THREAD

**Issue by jayhanbest** [ETH-NEXUS/scAmpi_single_cell_RNA#17]
Hi, I am trying to run multiple samples using scAmpi. I figured out that it is possible to change the sample name by modifying the file config/sample_map.tsv, but the workflow seems to fail to recognize multiple sample names when putting multiple sample names distinguished by tabs in the sample_map.tsv file. Is the scAmpi workflow able to run multiple samples together, or is it only possible to analyze one sample at a time?

**Comment by aricht** [comment]
Hi,
adapting `config/sample_map.tsv` is the right place to start when you want to run several samples in one run - which is possible with scAmpi.
The sample names are expected in a column with header "sample" in the tab-delimited `sample_map.tsv`, with one row per sample. See the description in the `README.md` file.
Best,
Anne
